openapi: 3.0.3
info:
  title: XIS Patient FHIR API
  version: 1.0.0

paths:
  /Patient:
    get:
      summary: Discover if a patient is registered at the organization.
      operationId: findPatient
      responses:
        '200':
          description: A bundle which contains a single Patient resource if the patient is registered at the organization.
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/PatientBundle'

components:
  schemas:
    PatientBundle:
      type: object
      required: [ resourceType, type ]
      properties:
        resourceType:
          type: string
          enum: [ Bundle ]
          example: Bundle
        meta:
          type: object
          properties:
            versionId:
              type: string
              example: "4037143"
        type:
          type: string
          enum: [ searchset ]
          example: searchset
        total:
          type: integer
          example: 1
        link:
          type: array
          items:
            type: object
            properties:
              relation:
                type: string
                example: "self"
              url:
                type: string
                example: "https://example.com/fhir/Patient"
        entry:
          type: array
          items:
            type: object
            required: [ resource ]
            properties:
              fullUrl:
                type: string
                example: "https://example.com/fhir/Patient/example-patient-id-1"
              resource:
                $ref: '#/components/schemas/Patient'
              search:
                type: object
                properties:
                  mode:
                    type: string
                    enum: [ match, include, outcome ]
                    example: "match"
    Patient:
      type: object
      required: [ resourceType, id, identifier ]
      properties:
        resourceType:
          type: string
          enum: [ Patient ]
          example: Patient
        id:
          type: string
          example: "example-patient-id-1"
        identifier:
          type: array
          items:
            type: object
            properties:
              system:
                type: string
                example: "http://fhir.nl/fhir/NamingSystem/bsn"
              value:
                type: string
                example: 123456782
