openapi: 3.0.3
info:
  title: Spreekuur.nl chat FHIR API
  version: 1.0.0

paths:
  /Communication:
    post:
      summary: Send message from XIS to Spreekuur.nl
      operationId: createCommunicationAtSpreekuur
      requestBody:
        required: true
        content:
          application/fhir+json:
            schema:
              $ref: '#/components/schemas/Communication'
      responses:
        '201':
          description: Communication created
  /Encounter:
    patch:
      summary: Close a chat
      operationId: closeChat
      requestBody:
        required: true
        content:
          application/fhir+json:
            schema:
              $ref: '#/components/schemas/Encounter'
      responses:
        '200':
          description: Chat closed
components:
  schemas:
    Communication:
      type: object
      required: [ resourceType, id, identifier, status, payload, encounter, recipient, sender, subject, category ]
      properties:
        resourceType:
          type: string
          enum: [ Communication ]
          example: Communication
        id:
          type: string
          example: 1234567890
        identifier:
          type: array
          items:
            type: object
            properties:
              system:
                type: string
                example: "nl.spreekuur.communication-id"
              value:
                type: string
                example: 1234567890
        status:
          type: string
          enum: [ completed ]
          example: completed
        payload:
          type: array
          items:
              type: object
              properties:
                contentString:
                  type: string
                  example: "Dit is een testbericht van Spreekuur.nl naar het XIS."
                contentAttachment:
                  type: object
                  properties:
                    contentType:
                      type: string
                      example: "jpeg"
                    url:
                      type: string
                      example: "http://test.local/test.jpg"
                    title:
                      type: string
                      example: "Test afbeelding"
        encounter:
          type: object
          properties:
            identifier:
              type: array
              items:
                type: object
                properties:
                  system:
                    type: string
                    example: "nl.example-xis.encounter-id"
                  value:
                    type: string
                    example: 1234567890
        sender:
          type: array
          items:
            type: object
            properties:
              reference:
                type: string
                example: "PractitionerRole/d131fb4e-e9fe-458f-9ec3-b55c80c2cd75"
        recipient:
          type: array
          items:
            type: object
            properties:
              identifier:
                type: array
                items:
                  type: object
                  properties:
                    system:
                      type: string
                      example: "http://fhir.nl/fhir/NamingSystem/bsn"
                    value:
                      type: string
                      example: 123456789
        subject:
          type: array
          items:
            type: object
            properties:
              identifier:
                type: array
                items:
                  type: object
                  properties:
                    system:
                        type: string
                        example: "http://fhir.nl/fhir/NamingSystem/bsn"
                    value:
                        type: string
                        example: 123456789
        category:
          type: array
          items:
            type: object
            properties:
              coding:
                type: array
                items:
                  type: object
                  properties:
                    system:
                      type: string
                      example: "nl.spreekuur.communication-type"
                    code:
                      type: string
                      example: "chat"
    Encounter:
        type: object
        required: [ resourceType, id, identifier, status, class, subject ]
        properties:
          resourceType:
            type: string
            enum: [ Encounter ]
            example: Encounter
          id:
            type: string
            example: 1234567890
          identifier:
            type: array
            items:
              type: object
              properties:
                system:
                  type: string
                  example: "https://example-xis.nl/encounter-id"
                value:
                  type: string
                  example: 1234567890
          status:
            type: string
            enum: [ finished ]
            example: finished
