openapi: 3.0.3
info:
  title: Spreekuur.nl Patient FHIR API
  version: 1.1.0

paths:
  /Patient/_search:
    post:
      summary: Discover if a patient has a Spreekuur.nl account.
      operationId: findPatient
      parameters:
        - name: "organization_agb"
          in: header
          description: The AGB code of the organization to search the patient in.
          required: true
          schema:
              type: string
              example: "12345678"
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - identifier
              properties:
                identifier:
                  type: string
                  description: |
                    The patient's BSN or Patient IDP ID in the format system|value
                    
                    Examples:
                    - Using BSN: `http://fhir.nl/fhir/NamingSystem/bsn|123456782`
                    - Using Patient IDP ID: `http://spreekuur.nl/fhir/NamingSystem/patientIdpId|d3641041-50c5-4141-b1eb-4e54d9bd0c15`
                  example: "http://fhir.nl/fhir/NamingSystem/bsn|123456782"
      responses:
        '200':
          description: A bundle which contains a single Patient resource if the patient is registered at the organization.
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/PatientBundle'
  /Patient:
    post:
      summary: Send invitation mail to a Patient to start using Spreekuur.nl
      parameters:
        - name: "organization_agb"
          in: header
          description: The AGB code of the organization to search the patient in.
          required: true
          schema:
            type: string
            example: "12345678"
      operationId: invitePatient
      requestBody:
        required: true
        content:
          application/fhir+json:
            schema:
              $ref: '#/components/schemas/PatientInvite'
      responses:
        '201':
          description: Patient invited

components:
  schemas:
    PatientBundle:
      type: object
      required: [ resourceType, type ]
      properties:
        resourceType:
          type: string
          enum: [ Bundle ]
          example: Bundle
        meta:
          type: object
          properties:
            versionId:
              type: string
              example: "4037143"
        type:
          type: string
          enum: [ searchset ]
          example: searchset
        total:
          type: integer
          example: 1
        entry:
          type: array
          items:
            type: object
            required: [ resource ]
            properties:
              resource:
                $ref: '#/components/schemas/Patient'
    Patient:
      type: object
      required: [ resourceType, id, identifier ]
      properties:
        resourceType:
          type: string
          enum: [ Patient ]
          example: Patient
        id:
          type: string
          example: 123456782
        identifier:
          type: array
          items:
            type: object
            properties:
              system:
                type: string
                example: "http://fhir.nl/fhir/NamingSystem/bsn"
              value:
                type: string
                example: 123456782
        extension:
          type: array
          items:
            type: object
            properties:
              url:
                type: string
                example: "http://spreekuur.nl/fhir/NamingSystem/spreekuurIdpId"
              valueString:
                type: string
                format: uuid
                example: "d3641041-50c5-4141-b1eb-4e54d9bd0c15"
    PatientInvite:
      type: object
      required: [ resourceType, id, identifier, telecom ]
      properties:
        resourceType:
          type: string
          enum: [ Patient ]
          example: Patient
        id:
          type: string
          example: "example-patient-id"
        identifier:
          type: array
          items:
            type: object
            required: [ system, value ]
            properties:
              system:
                type: string
                example: "http://fhir.nl/fhir/NamingSystem/bsn"
              value:
                type: string
                example: 123456782
        telecom:
          type: array
          items:
            type: object
            required: [ system, value ]
            properties:
              system:
                type: string
                enum: [ email ]
                example: email
              value:
                type: string
                example: "example-patient@example.local"
